name: Deploy to Firebase Hosting on Push

#Triger On Push
on: 
  push:
    branches: 
      - main

#Action When Trigered
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          - node-version: 14.15

      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
      - name: Deploy
        run: npm run deploy
        env:
          CI: true
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN }}""
